=== veloren/site/other-assets/schemas/music-works.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Musical works",
  "description": "The sound recordings used by Veloren",
  "type": "array",
  "items": {
    "type": "object",
    "required": ["name", "license", "type"],
    "additionalProperties": false,
    "properties": {
      "name": {
        "description": "The name of the music work",
        "type": "string"
      },
      "authors": {
        "description": "The people who made the music work",
        "type": [
          "string",
          "array"
        ],
        "items": {
          "type": "string"
        },
        "minItems": 1,
        "uniqueItems": true
      },
      "license": {
        "description": "The license applicable to the music work",
        "type": "string",
        "default": "GPL-3.0-or-later",
        "enum": [
          "GPL-3.0-or-later",
          "CC0-1.0",
          "CC-BY-4.0",
          "CC-BY-SA-4.0"
        ]
      },
      "type": {
        "description": "The type of musical work",
        "type": "string",
        "enum": [
          "theme",
          "sfx"
        ]
      }
    }
  }
}

=== veloren/site/content/attribution/music/works.json
[
  {
    "name": "veloren_title_tune.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "cavernous_hollow.ogg",
    "authors": "GeekyGami",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "down_the_rabbit_hole.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "mineral_deposits.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "saturated_hallows.ogg",
    "authors": "Flashbang",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "stars_like_stalactites.ogg",
    "authors": "DragonDee",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "barred_paths-end.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "barred_paths-loop.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "barred_paths-start.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "reversal-end.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "reversal-loop.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "reversal-start.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "cobbled_halls.ogg",
    "authors": "Austin Bowers (Crow)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "dank_dungeon.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "mysty_temple.ogg",
    "authors": "Tiny",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "ruination.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "sacred_temple.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "thrumming_waters.ogg",
    "authors": "Jeremiah Sweeney",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "vast_onslaught.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "a_cold_breeze_blows.ogg",
    "authors": "Stone Music Productions",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "a_heros_sorrow.ogg",
    "authors": "Benjam Soule H. Walker (Oolnokk)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "a_peaceful_moment.ogg",
    "authors": "ThanosFisherman",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "a_solemn_quest.ogg",
    "authors": "Eden",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "adventurous_soul.ogg",
    "authors": "Austin Bowers (Crow)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "ballerine_macabre.ogg",
    "authors": "GeekyGami",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "between_the_fairies.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "calling_wild.ogg",
    "authors": "Ultimafounding",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "calming_hills.ogg",
    "authors": "Ultimafounding",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "campfire_stories.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "drifting_along.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "ethereal_bonds.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "everbearing.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "field_grazing.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "follow_the_signs.ogg",
    "authors":"Benjam Soule H. Walker (Oolnokk)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "highland_of_the_hawk.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "into_the_dark_forest.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "jungle_ambient.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "just_the_beginning.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "leap_of_faith.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "limits.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "moonbeams.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "moonlit_canopy.ogg",
    "authors": "GeekyGami",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "oceania.ogg",
    "authors": "Eden",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "raising_below_like_thunder.ogg",
    "authors": "Rarnage",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "serene_meadows.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "short_meandering.ogg",
    "authors": "Ap1evideogame",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "snowtop_volume.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "song_of_the_eldwood.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "stargazing.ogg",
    "authors": "GeekyGami",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "the_heavens_weep.ogg",
    "authors": "Benjam Soule H. Walker (Oolnokk)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "the_undergrowth.ogg",
    "authors": "Benjam Soule H. Walker (Oolnokk)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "torii.ogg",
    "authors": "FaceImplosion",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "travel_by_night.ogg",
    "authors": "Benjam Soule H. Walker (Oolnokk)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "true_nature.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "verdant_glades.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "wandering_voices.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "winter_falls.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "a_rest_under_the_sunset.ogg",
    "authors": "phoenix13032005",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "a_tale_worth_telling.ogg",
    "authors": "Benjam Soule H. Walker (Oolnokk)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "bustle_and_bloom.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "fiesta_del_pueblo.ogg",
    "authors": "Aeronic",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "im_home.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "into_the_mines.ogg",
    "authors": "Stone Music Productions",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "life_of_a_background_mob.ogg",
    "authors": "GeekyGami",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "rest_assured.ogg",
    "authors": "Tomer (Badbbad)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "starlit_pathways.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "the_quiet_after_the_battle.ogg",
    "authors": "Tobias Thy",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "warmth_of_the_hearth.ogg",
    "authors": "Austin Bowers (Crow)",
    "license": "GPL-3.0-or-later",
    "type": "theme"
  },
  {
    "name": "cave.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "leaves.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "rain.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "thunder.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "wind.ogg",
    "authors": "DaforLynx",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "arrow_shot_1.ogg",
    "authors": "Ellinia",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "arrow_shot_2.ogg",
    "authors": "Ellinia",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "arrow_shot_3.ogg",
    "authors": "Ellinia",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "arrow_shot_4.ogg",
    "authors": "Ellinia",
    "license": "GPL-3.0-or-later",
    "type": "sfx"
  },
  {
    "name": "barrel_organ.ogg",
